### ISSUE TITLE
Error when downloading Stereo dataset

### ISSUE THREAD

**Issue by TomTomTommi** [ozendelait/rvc_devkit#38]
I run `python stereo_devkit.py` but it gets the error below:
```
Traceback (most recent call last):
  File "stereo_devkit.py", line 6, in <module>
    from benchmark_eth3d import *
  File "/home/jingjunpeng/rvc_devkit/stereo/benchmark_eth3d.py", line 4, in <module>
    from dataset_format_middlebury2014 import *
  File "/home/jingjunpeng/rvc_devkit/stereo/dataset_format_middlebury2014.py", line 4, in <module>
    from util import *
  File "/home/jingjunpeng/rvc_devkit/stereo/util.py", line 11, in <module>
    from rvc_download_helper import download_file_with_resume
  File "/home/jingjunpeng/rvc_devkit/common/rvc_download_helper.py", line 47
    print("Error: it looks like your python requests SSL verification is broken.",file=sys.stderr)
                                                                                      ^
SyntaxError: invalid syntax
```
Could you please help me to solve this?

**Comment by ozendelait** [comment]
Have a look at this solved issue:
https://github.com/ozendelait/rvc_devkit/issues/16

If you can't solve your SSL errors, then you can choose to skip the SSL checks by defining
export RVC_CUSTOM_SSL_SKIP_VERIFY=1
