### ISSUE TITLE
MVD Server Error (Semantic)

### ISSUE THREAD

**Issue by lambert-x** [ozendelait/rvc_devkit#65]
Hi, 

I submitted a zip file containing the 8-bit png predictions to the server and got the error in below. I think my submission is valid. Could you please have a look at it?
```

WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
Traceback (most recent call last):
  File "/tmp/codalab/tmpmTnF5k/run/program/raster_eval.py", line 13, in evaluate_image_pair
    pred = np.array(Image.open(pred_path)).astype(np.int64)
  File "/usr/local/lib/python3.8/dist-packages/Pillow-9.2.0-py3.8-linux-x86_64.egg/PIL/Image.py", line 3092, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/codalab/tmpmTnF5k/run/input/res/KYDNewfFShzSVSIeeek3oA.png'
Traceback (most recent call last):
  File "/tmp/codalab/tmpmTnF5k/run/program/raster_eval.py", line 13, in evaluate_image_pair
    pred = np.array(Image.open(pred_path)).astype(np.int64)
  File "/usr/local/lib/python3.8/dist-packages/Pillow-9.2.0-py3.8-linux-x86_64.egg/PIL/Image.py", line 3092, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/codalab/tmpmTnF5k/run/input/res/w6Uwc1xL9FFEy-u1rF0B-g.png'
Traceback (most recent call last):
  File "/tmp/codalab/tmpmTnF5k/run/program/raster_eval.py", line 13, in evaluate_image_pair
    pred = np.array(Image.open(pred_path)).astype(np.int64)
  File "/usr/local/lib/python3.8/dist-packages/Pillow-9.2.0-py3.8-linux-x86_64.egg/PIL/Image.py", line 3092, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/codalab/tmpmTnF5k/run/input/res/Yn2fWYJpDWZVwNsjEiFA7A.png'
Traceback (most recent call last):
  File "/tmp/codalab/tmpmTnF5k/run/program/raster_eval.py", line 13, in evaluate_image_pair
    pred = np.array(Image.open(pred_path)).astype(np.int64)
  File "/usr/local/lib/python3.8/dist-packages/Pillow-9.2.0-py3.8-linux-x86_64.egg/PIL/Image.py", line 3092, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/codalab/tmpmTnF5k/run/input/res/Mf4yT90SAKoUvraEoMAuew.png'
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/tmp/codalab/tmpmTnF5k/run/program/raster_eval.py", line 13, in evaluate_image_pair
    pred = np.array(Image.open(pred_path)).astype(np.int64)
  File "/usr/local/lib/python3.8/dist-packages/Pillow-9.2.0-py3.8-linux-x86_64.egg/PIL/Image.py", line 3092, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/codalab/tmpmTnF5k/run/input/res/w6Uwc1xL9FFEy-u1rF0B-g.png'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/tmp/codalab/tmpmTnF5k/run/program/run.py", line 87, in 
    miou, iou = evaluate(gtDir, resDir)
  File "/tmp/codalab/tmpmTnF5k/run/program/raster_eval.py", line 35, in evaluate
    for i, result in enumerate(results):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/codalab/tmpmTnF5k/run/input/res/w6Uwc1xL9FFEy-u1rF0B-g.png'
```

**Comment by ozendelait** [comment]
Please zip all pngs in a single zip file without subfolders. Also include a png for every benchmarking test image of MVD. Are the mentioned pngs in your submission (e.g. Yn2fWYJpDWZVwNsjEiFA7A.png, w6Uwc1xL9FFEy-u1rF0B-g.png) without additional folder hierarchies?

**Comment by lambert-x** [comment]
> Please zip all pngs in a single zip file without subfolders. Also include a png for every benchmarking test image of MVD. Are the mentioned pngs in your submission (e.g. Yn2fWYJpDWZVwNsjEiFA7A.png, w6Uwc1xL9FFEy-u1rF0B-g.png) without additional folder hierarchies?

My submission does not have additional folder hierarchies. It is just a zip file containing the pngs.

**Comment by ozendelait** [comment]
And the files Yn2fWYJpDWZVwNsjEiFA7A.png or  w6Uwc1xL9FFEy-u1rF0B-g.png are present in the zip file?

**Comment by lambert-x** [comment]
Yes, they are in the zip. > And the files Yn2fWYJpDWZVwNsjEiFA7A.png or  w6Uwc1xL9FFEy-u1rF0B-g.png are present in the zip file?

**Comment by ozendelait** [comment]
@acolovic  Please check the MVD semantic segm. submission system.
@lambert-x  Please continue to submit to the remaining benchmark sites

**Comment by lambert-x** [comment]
> @acolovic Please check the MVD semantic segm. submission system. @lambert-x Please continue to submit to the remaining benchmark sites

I have successfully submitted results to all the other 5 benchmarks. I have two questions about the MVD label mapping.

1. What value should I set for the pixels should be assigned to "unlabeled"? 

2. Bird is 0 or 1? In the https://github.com/ozendelait/rvc_devkit/blob/master/segmentation/ss_mapping_uint8.csv and the https://codalab.lisn.upsaclay.fr/competitions/5821#learn_the_details-evaluation,  "bird" is set to 0 while the https://github.com/ozendelait/rvc_devkit/blob/master/segmentation/README.md says it should be 1.

**Comment by lambert-x** [comment]
> @acolovic Please check the MVD semantic segm. submission system. @lambert-x Please continue to submit to the remaining benchmark sites

I have successfully submitted my result. The only thing I need is to update the rvc leaderboard. Thanks a lot.

**Comment by ozendelait** [comment]
Great, please post the username<->method link here:
https://github.com/ozendelait/rvc_devkit/issues/66
