### ISSUE TITLE
Something wrong when downloading VIPER Dataset

### ISSUE THREAD

**Issue by Carol-lyh** [ozendelait/rvc_devkit#74]
When executing the download script download_sem_segm.sh, something wrong happens in downloading VIPER
`Extracting archive: /data/Datasets//viper/inst_train_00-77_0.zip
Traceback (most recent call last):
  File "download_viper.py", line 14, in <module>
    v_downl.DownloadAndUnpack(archive_dir_path, unpack_dir_path, {})
  File "/data/rvc_devkit/segmentation/legacy/benchmark_viper.py", line 98, in DownloadAndUnpack
    UnzipFile(archive_path, unpack_dir_path)
  File "/data/rvc_devkit/segmentation/legacy/util.py", line 155, in UnzipFile
    zip_ref = zipfile.ZipFile(open(file_path, 'rb'))
  File "/home/liulin/anaconda3/envs/SIW/lib/python3.7/zipfile.py", line 1258, in __init__
    self._RealGetContents()
  File "/home/liulin/anaconda3/envs/SIW/lib/python3.7/zipfile.py", line 1325, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file`
Seems to have problems with the downloaded zip file.

**Comment by ozendelait** [comment]
Looks like the AWS bucket was renamed or removed; https://viper-dataset.s3.amazonaws.com/train_img_00-77_0_jpg.zip from the devkit returns `<Error><Code>NoSuchBucket</Code><Message>The specified bucket does not exist</Message><BucketName>viper-dataset</BucketName> [...]`
@srrichter please check the AWS bucket

**Comment by srrichter** [comment]
Sorry, I can't do anything about that. The AWS bucket was a mirror that Tsung-Yi Lin created. The original VIPER archives are still available through our download page.
